[WIP]Support Oauth2
streamnative/function-mesh-worker-service pull request #357
Opened 2022-08-19 08:10 UTC by jiangpengcheng

resolve: #334

2022-08-19 09:26 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/auth/AuthHandlerOauth.java
> +        return clientRole.split("@")[0];
maybe use a more common way, like `clientRole.replaceAll("[@./_]", "-")`?

2022-08-24 18:26 UTC, nlu90 requested changes
Please update based on our last night's discussion

2022-08-24 18:26 UTC, nlu90 commented on src/main/java/io/functionmesh/compute/auth/AuthHandler.java
> +    String SOURCE_COMPONENT = "Source";
some consts here are duplicated with ones in the `CommonUtil`.
We should reuse them

2022-08-24 18:26 UTC, nlu90 commented on src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
> +                            v1alpha1Function.getSpec().getClusterName(), tenant, namespace, functionName, results.getAuthSecretData(), worker());
try not to create a new secret here:
1. it will be hard to manage in the long run at scale
2. later the secret is loaded as ENVs
Directly generating these ENVs into component definition will be better.

2022-08-25 02:18 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
> +                            v1alpha1Function.getSpec().getClusterName(), tenant, namespace, functionName, results.getAuthSecretData(), worker());
agree

2022-08-25 02:18 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/auth/AuthHandler.java
> +    String SOURCE_COMPONENT = "Source";
ok

2022-08-26 01:50 UTC, tuteng commented on src/main/java/io/functionmesh/compute/auth/AuthHandlerOauth.java
> +                Oauth2Parameters oauth2Parameters = mapper.readValue(params, Oauth2Parameters.class);
Maybe its name should be OAuth => https://en.wikipedia.org/wiki/OAuth

2022-08-26 06:55 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/auth/AuthHandlerOauth.java
> +                Oauth2Parameters oauth2Parameters = mapper.readValue(params, Oauth2Parameters.class);
good point

2022-08-26 07:38 UTC, jiangpengcheng commented
I will add some integration tests aginst pulsar using oauth2

2022-08-30 03:48 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
> +                            v1alpha1Function.getSpec().getClusterName(), tenant, namespace, functionName, results.getAuthSecretData(), worker());
after test, it cannot be done since the `FunctionMesh` won't add the `--auth-plugin` and `--auth-params` to commands if the `Spec.pulsar.authSecret` is not specified, so we must create a new **authSecret**

2022-09-01 09:46 UTC, jiangpengcheng commented on .ci/clusters/mesh_worker_service_integration_test_pulsar_config.yaml
> +  webServiceURL: http://sn-platform-pulsar-broker.default.svc.cluster.local:8080
when this pr: https://github.com/streamnative/charts/pull/855 is merged, we can change it back to `proxy`'s endpoint

2022-09-01 09:50 UTC, jiangpengcheng commented on src/main/java/io/functionmesh/compute/models/OAuth2Parameters.java
> +        m.put("private_key", this.privateKey.replace("file://", ""));
python runtime(which using pulsar-cpp-client) doesn't handle the `file://` prefix, so need to remove it for python runtime

2022-09-02 22:26 UTC, nlu90 submitted a review, later dismissed

2022-09-06 16:42 UTC, nlu90 approved these changes

2022-09-06 23:08 UTC, tuteng approved these changes

2022-09-07 21:14 UTC, merged