support logging configurations
streamnative/function-mesh-worker-service pull request #401
Opened 2022-09-20 08:34 UTC by tpiperatgod

Signed-off-by: laminar <tpiperatgod@gmail.com>

2022-09-26 20:11 UTC, nlu90 commented on src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
> +                userConfig.remove(LOGGING_LEVEL_KEY);
Why do we need to remove this?

2022-09-27 06:05 UTC, tpiperatgod commented on src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
> +                userConfig.remove(LOGGING_LEVEL_KEY);
Because I think these two fields are added by mesh-worker-service and should not be considered as user-defined configurations. 

I think it's OK to keep them if they don't cause users any confusion by not removing these two fields...

2022-09-28 01:37 UTC, freeznet requested changes
please avoid using `UserConfig` for customizable configs added by function-mesh.

2022-09-28 01:37 UTC, freeznet commented on src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
> +        Map<String, Object> userConfig = functionConfig.getUserConfig();
The new configs added by function mesh should be defined in `CustomRuntimeOptions`, and you can access to it by https://github.com/streamnative/function-mesh-worker-service/blob/branch-2.10.1/src/main/java/io/functionmesh/compute/util/FunctionsUtil.java#L87-L88

`UserConfig` is bound to the function context so the function's implementation could access it if the function requires some additional configs, usually the user will pass such function customized configs via `UserConfig`, and pass runtime customized configs via `CustomRuntimeOptions`.

2022-09-29 07:44 UTC, tpiperatgod commented on src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
> +        Map<String, Object> userConfig = functionConfig.getUserConfig();
done

2022-10-11 01:12 UTC, freeznet approved these changes

2022-10-11 01:13 UTC, merged